### ISSUE TITLE
Set time to day upon starting a match

### ISSUE THREAD

**Issue by SquarePlayn** [Extremelyd1/minecraft-bingo#20]
Currently, the ingame day-cycle time is not affected when the game starts (afaik). If you wait long in pre-game or if you play a 2nd match after the first match, it may not be early in the day anymore. While a `/time set day` command is easily issued, it'd be nice if this was done automatically for consistency and ease of use.
Even better if it's togglable.

**Comment by Extremelyd1** [comment]
The ingame day-cycle is frozen and set to `0` upon loading the world and only unfrozen as soon as the game starts. So this can only pose an issue when playing a 2nd match as you mentioned. However, playing a 2nd match is not officially supported, as the world is already affected by the first match. And after loading a new (or the backup old) world after reboot, this should not pose an issue due to the above mentioned.
